sudo: required
services:
    - docker
before_install:
    - docker build -t vtolle/docker-react -f Dockerfile.dev .
script:
    - docker run -e CI=true vtolle/docker-react npm run test
#    - docker run -e CI=true vtolle/docker-react npm run test -- --watchAll=false
